# Generated by Django 2.0.2 on 2018-06-09 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=255)),
                ('phoneNum', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('buildingPermitNum', models.IntegerField(default=0)),
                ('plumbingPermitNum', models.IntegerField(default=0)),
                ('electricPermitNum', models.IntegerField(default=0)),
                ('zoningPermitNum', models.IntegerField(default=0)),
                ('mechanicalPermitNum', models.IntegerField(default=0)),
                ('signPermitNum', models.IntegerField(default=0)),
                ('pManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
