# Generated by Django 2.0.2 on 2018-06-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180609_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='editer',
        ),
    ]
