# Generated by Django 2.0.2 on 2018-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180610_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='BP_Confirmation_Time',
            field=models.CharField(default='00/00/2018', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='Builing_Plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='Electric_Plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='Mechanical_Plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='Plumbing_Plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='Sign_Plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='Zoning_Plan',
            field=models.IntegerField(default=0),
        ),
    ]
