# Generated by Django 2.0.2 on 2018-06-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180611_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Builing_Plan',
            new_name='Building_Plan',
        ),
    ]
