# Generated by Django 2.0.2 on 2018-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_Code', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('Permit_Num', models.IntegerField(default=0)),
                ('Type_of_Inspection', models.CharField(max_length=255)),
                ('Step', models.CharField(max_length=255)),
                ('Inspection_Time', models.CharField(default='00/00/0000', max_length=255)),
                ('Inspector_Name', models.CharField(max_length=255)),
                ('phone_Number', models.CharField(max_length=255)),
            ],
        ),
    ]
