# Generated by Django 2.0.2 on 2018-06-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='District',
            field=models.CharField(default='Central District', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='Result',
            field=models.CharField(default='In Progress', max_length=255),
        ),
    ]
